name: Build Mod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet Packages
      run: nuget restore TurboDrifterGoose.sln
      continue-on-error: true

    - name: Build Solution
      run: msbuild TurboDrifterGoose.sln /p:Configuration=Release

    - name: Upload Mod DLL
      uses: actions/upload-artifact@v4
      with:
        name: TurboDrifterGoose-DLL
        path: |
          **/bin/Release/**/TurboDrifterGoose.dll
          **/bin/Release/TurboDrifterGoose.dll
